### ISSUE TITLE
[geth-test-app] init config / configuration

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/eth-react-native-daemon#3]
Hi,

since we somehow have to configure the node we need to be able to generate a config / set it. 

Interesting methods are probably: 

- [`(instancetype)init:(NSString*)datadir config:(GethNodeConfig*)config;`](https://github.com/Bit-Nation/eth-react-native-daemon/blob/master/gethTestApp/ios/Geth.framework/Versions/A/Headers/Geth.objc.h#L1064)

- [`@interface GethNodeConfig : NSObject <goSeqRefInterface>`](https://github.com/Bit-Nation/eth-react-native-daemon/blob/master/gethTestApp/ios/Geth.framework/Versions/A/Headers/Geth.objc.h#L1094)

**Comment by albertoestarrona** [comment]
We are using:
 configGeth = GethNewNodeConfig();
  [configGeth setEthereumEnabled:true];
  [configGeth setEthereumNetworkID:3];
  GethEnodes *enodes = GethNewEnodes(16);
  enodes = GethFoundationBootnodes();
... 
and:
node = GethNewNode(networkDir, configGeth, &error);

But looks like in 1.7.2 there's no way to inject (--rpc) on the node config at start. They suggest to use a EtheriumClient, to have access to the submodules of the API:

EthClient = GethNewEthereumClient(@"http://localhost:8545", &error);

But we still need to use the RPC protocol through the iOS code: (reference)
https://ethereum.stackexchange.com/questions/19261/how-to-access-the-event-log-by-knowing-the-contract-address-golang/19330#19330

**Comment by albertoestarrona** [comment]
We made some direct changes to the Geth lib, so we could enabled the HTTP Port ("http://localhost:8545")
